### ISSUE TITLE
Error reported during training phase

### ISSUE THREAD

**Issue by zshuo7615** [FoundationVision/VAR#33]
Hello, would you like to ask how to solve the following error during training in version torch=2.0.1?

[04-22 21:18:11] (ata/private/VAR/train.py, line  41)=> [build PT data] ...

[04-22 21:18:11] (rivate/VAR/utils/data.py, line  34)=> [Dataset] len(train_set)=17028, len(val_set)=3552, num_classes=1000
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  48)=> Transform [train] = 
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> Resize(size=288, interpolation=lanczos, max_size=None, antialias=warn)
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> RandomCrop(size=(256, 256), padding=None)
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> ToTensor()
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> <function normalize_01_into_pm1 at 0x7f51d2e66a70>
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  54)=> ---------------------------

[04-22 21:18:11] (rivate/VAR/utils/data.py, line  48)=> Transform [val] = 
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> Resize(size=288, interpolation=lanczos, max_size=None, antialias=warn)
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> CenterCrop(size=(256, 256))
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> ToTensor()
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  51)=> <function normalize_01_into_pm1 at 0x7f51d2e66a70>
[04-22 21:18:11] (rivate/VAR/utils/data.py, line  54)=> ---------------------------

[04-22 21:18:11] (ata/private/VAR/train.py, line  64)=> [auto_resume] no ckpt found @ /opt/data/private/VAR/local_output/ar-ckpt*.pth
[04-22 21:18:11] (ata/private/VAR/train.py, line  64)=> [auto_resume quit]
[04-22 21:18:11] (ata/private/VAR/train.py, line  65)=> [dataloader multi processing] ...     [dataloader multi processing](*) finished! (0.00s)
[04-22 21:18:11] (ata/private/VAR/train.py, line  71)=> [dataloader] gbs=1, lbs=1, iters_train=17028, types(tr, va)=('DatasetFolder', 'DatasetFolder')
[04-22 21:18:11] (rivate/VAR/models/var.py, line  98)=> 
[constructor]  ==== flash_if_available=True (0/16), fused_if_available=True (fusing_add_ln=0/16, fusing_mlp=0/16) ==== 
    [VAR config ] embed_dim=1024, num_heads=16, depth=16, mlp_ratio=4.0
    [drop ratios ] drop_rate=0.0, attn_drop_rate=0.0, drop_path_rate=0.0666667 (tensor([0.0000, 0.0044, 0.0089, 0.0133, 0.0178, 0.0222, 0.0267, 0.0311, 0.0356,
        0.0400, 0.0444, 0.0489, 0.0533, 0.0578, 0.0622, 0.0667]))

[04-22 21:18:12] (rivate/VAR/models/var.py, line 239)=> [init_weights] VAR with init_std=0.0180422
Traceback (most recent call last):
  File "/opt/data/private/VAR/train.py", line 334, in <module>
    try: main_training()
  File "/opt/data/private/VAR/train.py", line 180, in main_training
    ) = build_everything(args)
  File "/opt/data/private/VAR/train.py", line 98, in build_everything
    vae_local.load_state_dict(torch.load(vae_ckpt, map_location='cpu'), strict=True)
  File "/opt/data/private/VAR/models/vqvae.py", line 95, in load_state_dict
    return super().load_state_dict(state_dict=state_dict, strict=strict, assign=assign)
TypeError: Module.load_state_dict() got an unexpected keyword argument 'assign'

**Comment by karrykkk** [comment]
Same issue🥹

**Comment by keyu-tian** [comment]
hi @zshuo7615 maybe you can delete that arg named 'assign', or upgrade your torch to >= 2.1
